### ISSUE TITLE
Palve

### ISSUE THREAD

**Issue by romilrobtsenkov** [hinrek/Suvepraktika#12]
palun kasutage master branchi põhilisena, teeksite minu elu lihtsamaks.

koodi osas etteheiteid pole.

Kui tahate teha kasutajalugusid, siis need peaksid olema lühemad ja detailsema. Nt otsingu võimalus eraldi, mis kirjeldab ka mille järgi saab otsida ja filtreerida jne.

Olen suhteliselt võõras Pythoni keskkonna seadmise osas, võib-olla täpsustaks, et minu arvates võiks olla confi fail, kus vajalikud nt ABi sätted. Kas hoiate ENV\is kuidagi, siis mis kujul see on ja kas selle kuju peaks äkki kirjeldama README paigaldusjuhendis.

**Comment by hinrek** [comment]
Django-working on "master" branch, seadetest muudetud. Juhul, kui tegid clone vanale master branchile siis trüki meie repos (kaustas) olles `git checkout Django-working`.

Meil tekib andmebaas (sqlite3) automaatselt ja peale `python manage.py migrate` käsku. Selleks seaded on `mysite/settings.py` failis. Ehk pole postgre peale üle vaja minna, sest andmeid on väga vähe ja sqlite on väga võimekas. README failis käskudest peaks piisama keskkonna paigaldamiseks. Kas jääd hätta mingi etapi juures?

**Comment by romilrobtsenkov** [comment]
Kuna uuendan kõigi reposid, siis tülikas kui teie põhiline branch ei kanna nime master. Kui saad siis liiguta see node'i osa eraldi branchile ning merge'i Django-working masterisse. 

Hetkel ei ole veel paigaldamist proovinud, arvan et jääb nv peale.

**Comment by hinrek** [comment]
@romilrobtsenkov  Tegin merge "Django-working" -> "master". Teeme commite hetkel ikka Django-working branchi sisse ja siis mingi aja tagant merge uuesti.

**Comment by romilrobtsenkov** [comment]
Super sobib!
